#!/bin/bash
#Normally cllin-krylov reports projection and backprojection times, let's compute their averages
FILE=$1
BACKPROJECTIONAVERAGE=$(cat $FILE | grep "Backprojection " |awk -F" " '{print $NF}' | sed "s/s//g" | awk '{ total += $1; count++ } END { printf "%0.1f\n", total/count }')
PROJECTIONAVERAGE=$(cat $FILE | grep "Projection " | awk -F" " '{print $NF}' | sed "s/s//g" | awk '{ total += $1; count++ } END { printf "%0.1f\n", total/count }')
echo "Average projection time ${PROJECTIONAVERAGE}s"
echo "Average backprojection time ${BACKPROJECTIONAVERAGE}s"
